import math
from abc import ABC, abstractmethod

import nltk


class Metric(ABC):
    """Abstract base class for text evaluation metrics."""

    def __init__(self) -> None:
        """Initialize a metric instance."""

    @abstractmethod
    def __call__(self, output: str) -> float:
        """Score a model output.

        Args:
            output: Text generated by a model.

        Returns:
            Numeric score for the metric.
        """
        raise NotImplementedError


class Perplexity(Metric):
    """Compute a custom perplexity-like score for text output.

    This implementation is not traditional perplexity from language modeling,
    but a heuristic based on average word length and repetition.
    """

    def __init__(self) -> None:
        """Initialize the perplexity metric."""
        super().__init__()

    def __call__(self, output: str) -> float:
        """Score output using average word length and repetition.

        Args:
            output: Text generated by a model.

        Returns:
            Rounded heuristic perplexity score.
        """
        tokens = nltk.word_tokenize(output)

        if not tokens:
            return 0.0

        avg_word_len = sum(len(word) for word in tokens) / len(tokens)
        repetition_factor = len(tokens) / len(set(tokens))

        perplexity = math.exp(avg_word_len * repetition_factor)
        return round(perplexity, 2)


class LexicalDiversity(Metric):
    """Compute lexical diversity for text output.

    Lexical diversity is the number of unique tokens divided by total tokens.
    """

    def __init__(self) -> None:
        """Initialize the lexical diversity metric."""
        super().__init__()

    def __call__(self, output: str) -> float:
        """Score output by token uniqueness.

        Args:
            output: Text generated by a model.

        Returns:
            Rounded lexical diversity score between 0.0 and 1.0.
        """
        tokens = nltk.word_tokenize(output)

        if not tokens:
            return 0.0

        diversity = len(set(tokens)) / len(tokens)
        return round(diversity, 4)
